version: "3"

services:
  node:
    build:
      context: .docker/node
    working_dir: /usr/src/app
    command: npm run watch
    links:
      - mysql
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"

  mysql:
    image: mysql:5.7
    container_name: custom_cms_db
    restart: unless-stopped
    tty: true
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./.docker/db/data}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./.docker/db/logs}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}