/*CREATE DATABASE IF NOT EXISTS*/
CREATE DATABASE IF NOT EXISTS custom_cms;
/*Use custom_cms database*/
USE custom_cms;
/* CREATE TABBLE IF NOT EXISTS*/
CREATE TABLE IF NOT EXISTS articles (
    _id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    post_date DATE,
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;